export { default as Table } from './table.js'
export { default as TableHead } from './table-head.js'
export { default as TableBody } from './table-body.js'
export { default as TableCell } from './table-cell.js'
export { default as TableRow } from './table-row.js'
export { default as TableCaption } from './table-caption.js'
