export { default as Table } from './table.jsx'
export { default as TableHead } from './table-head.jsx'
export { default as TableBody } from './table-body.jsx'
export { default as TableCell } from './table-cell.jsx'
export { default as TableRow } from './table-row.jsx'
export { default as TableCaption } from './table-caption.jsx'
